"""add notes to product_input

Revision ID: 174c05e4503a
Revises: 167fba182586
Create Date: 2025-10-31 15:40:04.379982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174c05e4503a'
down_revision: Union[str, Sequence[str], None] = '167fba182586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_inputs', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_inputs', 'notes')
    # ### end Alembic commands ###
